local L = select(2, ...).L('zhTW')

L["MDP_TITLE"] = "英雄之路傳送門"

-- Expansions
L["Cataclysm"] = "浩劫與重生"
L["Mists of Pandaria"] = "潘達利亞之謎"
L["Warlords of Draenor"] = "德拉諾之霸"
L["Legion"] = "軍臨天下"
L["Battle for Azeroth"] = "決戰艾澤拉斯"
L["Shadowlands"] = "暗影之境"
L["Dragonflight"] = "巨龍崛起"
L["War Within"] = "地心之戰"
L["Current Season"] = "本賽季"

-- Dungeons
L["DUNGEON_TEMPLE_OF_THE_JADE_SERPENT"] = "玉蛟寺"
L["DUNGEON_SIEGE_OF_NIUZAO"] = "圍攻怒兆寺"
L["DUNGEON_SCHOLOMANCE"] = "通靈學院"
L["DUNGEON_SCARLET_MONASTERY"] = "血色修道院"
L["DUNGEON_SCARLET_HALLS"] = "血色大廳"
L["DUNGEON_GATE_OF_THE_SETTING_SUN"] = "落陽關"
L["DUNGEON_MOGUSHAN_PALACE"] = "魔古山宮"
L["DUNGEON_SHADO_PAN_MONASTERY"] = "影潘僧院"
L["DUNGEON_STORMSTOUT_BREWERY"] = "風暴烈酒酒坊"
L["DUNGEON_SHADOWMOON_BURIAL_GROUNDS"] = "影月墓地"
L["DUNGEON_EVERBLOOM"] = "永茂林"
L["DUNGEON_BLOODMAUL_SLAG_MINES"] = "血槌熔渣礦場"
L["DUNGEON_AUCHINDOUN"] = "奧齊頓"
L["DUNGEON_SKYREACH"] = "擎天峰"
L["DUNGEON_UPPER_BLACKROCK_SPIRE"] = "黑石塔上層"
L["DUNGEON_GRIMRAIL_DEPOT"] = "恐軌車站"
L["DUNGEON_IRON_DOCKS"] = "鋼鐵碼頭"
L["DUNGEON_DARKHEART_THICKET"] = "暗心灌木林"
L["DUNGEON_BLACK_ROOK_HOLD"] = "玄鴉堡"
L["DUNGEON_HALLS_OF_VALOR"] = "英靈殿"
L["DUNGEON_NELTHARIONS_LAIR"] = "奈薩里奧巢穴"
L["DUNGEON_COURT_OF_STARS"] = "眾星之廷"
L["DUNGEON_KARAZHAN"] = "重返卡拉贊"
L["DUNGEON_ATALDAZAR"] = "阿塔達薩"
L["DUNGEON_FREEHOLD"] = "自由港"
L["DUNGEON_WAYCREST_MANOR"] = "威奎斯特莊園"
L["DUNGEON_THE_UNDERROT"] = "幽腐深窟"
L["DUNGEON_MECHAGON"] = "機械岡行動"
L["DUNGEON_THE_NECROTIC_WAKE"] = "死靈戰地"
L["DUNGEON_PLAGUEFALL"] = "瘟疫之臨"
L["DUNGEON_MISTS_OF_TIRNA_SCITHE"] = "特那希迷霧"
L["DUNGEON_HALLS_OF_ATONEMENT"] = "贖罪之殿"
L["DUNGEON_SPIRES_OF_ASCENSION"] = "晉升之巔"
L["DUNGEON_THEATRE_OF_PAIN"] = "苦痛劇場"
L["DUNGEON_DE_OTHER_SIDE"] = "彼界境地"
L["DUNGEON_SANGUINE_DEPTHS"] = "血紅深淵"
L["DUNGEON_TAZAVESH_THE_VEILED_MARKET"] = "『帷幕市集』塔札維許 "
L["DUNGEON_RUBY_LIFE_POOLS"] = "晶紅生命之池"
L["DUNGEON_NOKHUD_OFFENSIVE"] = "諾庫德進攻據點"
L["DUNGEON_AZURE_VAULT"] = "蒼藍密庫"
L["DUNGEON_ALGETHAR_ACADEMY"] = "阿爾蓋薩學院"
L["DUNGEON_ULDAMAN"] = "奧達曼：提爾的遺產"
L["DUNGEON_NELTHARUS"] = "奈薩魯斯堡"
L["DUNGEON_BRACKENHIDE_HOLLOW"] = "蕨皮谷"
L["DUNGEON_HALLS_OF_INFUSION"] = "灌注迴廊"
L["DUNGEON_VORTEX_PINNACLE"] = "漩渦尖塔"
L["DUNGEON_THRONE_OF_THE_TIDES"] = "海潮王座"
L["DUNGEON_DAWN_OF_THE_INFINITE"] = "恆龍黎明"
L["DUNGEON_CITY_OF_THREADS"] = "蛛絲城"
L["DUNGEON_ARA_KARA_CITY_OF_ECHOS"] = "『回音之城』厄拉卡拉"
L["DUNGEON_STONEVAULT"] = "石庫"
L["DUNGEON_DAWNBREAKER"] = "破曉者號"
L["DUNGEON_THE_ROOKERY"] = "培育所"
L["DUNGEON_DARKFLAME_CLEFT"] = "暗焰裂縫"
L["DUNGEON_CINDERBREW_BREWERY"] = "燼釀酒莊"
L["DUNGEON_PRIORY_OF_THE_SACRED_FLAME"] = "聖焰隱修院"
L["DUNGEON_GRIM_BATOL"] = "格瑞姆巴托"
L["DUNGEON_SEIGE_OF_BORALUS"] = "波拉勒斯圍城戰"

-- Raids
L["RAID_VAULT_OF_THE_INCARNATES"] = "洪荒化身牢獄"
L["RAID_ABBERUS_THE_SHADOWED_CRUCIBLE"] = "『朧影實驗場』亞貝魯斯"
L["RAID_AMIRDRASSIL_THE_DREAMS_HOPE"] = "『夢境希望』埃達希爾"
L["RAID_CASTLE_NATHRIA"] = "納撒亞城"
L["RAID_SANCTUM_OF_DOMINATION"] = "統御聖所"
L["RAID_SEPULCHER_OF_THE_FIRST_ONES"] = "首創者聖塚"

-- Settings
L["LEFT_CLICK"] = "左鍵開啟傳送門"
L["RIGHT_CLICK"] = "右鍵開啟設定"
L["SHOW_BACKGROUNDS"] = "顯示/隱藏背景"
L["SHOW_MINIMAP"] = "顯示/隱藏小地圖圖標"
L["SETTINGS_TITLE"] = "英雄之路傳送門設定"
