local L = select(2, ...).L('ptBR')

L["MDP_TITLE"] = "Portais de Masmorras Míticas"

-- Expansões
L["Cataclysm"] = "Cataclysm"
L["Mists of Pandaria"] = "Mists of Pandaria"
L["Warlords of Draenor"] = "Warlords of Draenor"
L["Legion"] = "Legion"
L["Battle for Azeroth"] = "Battle for Azeroth"
L["Shadowlands"] = "Shadowlands"
L["Dragonflight"] = "Dragonflight"
L["War Within"] = "War Within"
L["Current Season"] = "Temporada Atual"

-- Masmorras
L["DUNGEON_TEMPLE_OF_THE_JADE_SERPENT"] = "Templo da Serpente de Jade"
L["DUNGEON_SIEGE_OF_NIUZAO"] = "Cerco ao Templo Niuzao"
L["DUNGEON_SCHOLOMANCE"] = "Scolomântia"
L["DUNGEON_SCARLET_MONASTERY"] = "Monastério Escarlate"
L["DUNGEON_SCARLET_HALLS"] = "Salões Escarlates"
L["DUNGEON_GATE_OF_THE_SETTING_SUN"] = "Portão do Sol Poente"
L["DUNGEON_MOGUSHAN_PALACE"] = "Palácio Mogu'shan"
L["DUNGEON_SHADO_PAN_MONASTERY"] = "Monastério Shado-Pan"
L["DUNGEON_STORMSTOUT_BREWERY"] = "Cervejaria Malte do Trovão"
L["DUNGEON_SHADOWMOON_BURIAL_GROUNDS"] = "Sepulcrário da Lua Negra"
L["DUNGEON_EVERBLOOM"] = "Floretérnia"
L["DUNGEON_BLOODMAUL_SLAG_MINES"] = "Minas de Escória do Malho Sangrento"
L["DUNGEON_AUCHINDOUN"] = "Auchindoun"
L["DUNGEON_SKYREACH"] = "Beira-céu"
L["DUNGEON_UPPER_BLACKROCK_SPIRE"] = "Pico da Rocha Negra Superior"
L["DUNGEON_GRIMRAIL_DEPOT"] = "Terminal Malho Imponente"
L["DUNGEON_IRON_DOCKS"] = "Docas de Ferro"
L["DUNGEON_DARKHEART_THICKET"] = "Bosque Corenegro"
L["DUNGEON_BLACK_ROOK_HOLD"] = "Castelo Corvo Negro"
L["DUNGEON_HALLS_OF_VALOR"] = "Salões da Bravura"
L["DUNGEON_NELTHARIONS_LAIR"] = "Covil de Neltharion"
L["DUNGEON_COURT_OF_STARS"] = "Pátio das Estrelas"
L["DUNGEON_KARAZHAN"] = "Karazhan"
L["DUNGEON_ATALDAZAR"] = "Atal'Dazar"
L["DUNGEON_FREEHOLD"] = "Angra do Facão"
L["DUNGEON_WAYCREST_MANOR"] = "Mansão Capelo"
L["DUNGEON_THE_UNDERROT"] = "Terra Podre"
L["DUNGEON_MECHAGON"] = "Mecagon"
L["DUNGEON_THE_NECROTIC_WAKE"] = "O Despertar Necrótico"
L["DUNGEON_PLAGUEFALL"] = "Pragaqueda"
L["DUNGEON_MISTS_OF_TIRNA_SCITHE"] = "Brumas de Tirna Scithe"
L["DUNGEON_HALLS_OF_ATONEMENT"] = "Salões da Expiação"
L["DUNGEON_SPIRES_OF_ASCENSION"] = "Torres da Ascensão"
L["DUNGEON_THEATRE_OF_PAIN"] = "Teatro da Dor"
L["DUNGEON_DE_OTHER_SIDE"] = "O Outro Lado"
L["DUNGEON_SANGUINE_DEPTHS"] = "Profundezas Sanguinárias"
L["DUNGEON_TAZAVESH_THE_VEILED_MARKET"] = "Tazavesh, o Mercado Velado"
L["DUNGEON_RUBY_LIFE_POOLS"] = "Poços de Vida Rubi"
L["DUNGEON_NOKHUD_OFFENSIVE"] = "Ofensiva Nokhud"
L["DUNGEON_AZURE_VAULT"] = "Câmara Lazúli"
L["DUNGEON_ALGETHAR_ACADEMY"] = "Academia Algethar"
L["DUNGEON_ULDAMAN"] = "Uldaman"
L["DUNGEON_NELTHARUS"] = "Neltharus"
L["DUNGEON_BRACKENHIDE_HOLLOW"] = "Covil Cascotenro"
L["DUNGEON_HALLS_OF_INFUSION"] = "Salões da Infusão"
L["DUNGEON_VORTEX_PINNACLE"] = "Pináculo do Vórtice"
L["DUNGEON_THRONE_OF_THE_TIDES"] = "Trono das Marés"
L["DUNGEON_DAWN_OF_THE_INFINITE"] = "Amanhecer do infinito"
L["DUNGEON_CITY_OF_THREADS"] = "Cidade dos Fios"
L["DUNGEON_ARA_KARA_CITY_OF_ECHOS"] = "Ara'kara, Cidade dos Ecos"
L["DUNGEON_STONEVAULT"] = "Cofre de Pedra"
L["DUNGEON_DAWNBREAKER"] = "Quebradia do Alvorecer"
L["DUNGEON_THE_ROOKERY"] = "O Pombal"
L["DUNGEON_DARKFLAME_CLEFT"] = "Fenda Chama Negra"
L["DUNGEON_CINDERBREW_BREWERY"] = "Cervejaria Cinzaferro"
L["DUNGEON_PRIORY_OF_THE_SACRED_FLAME"] = "Priorado da Chama Sagrada"
L["DUNGEON_GRIM_BATOL"] = "Grim Batol"
L["DUNGEON_SEIGE_OF_BORALUS"] = "Assédio a Boralus"
L["DUNGEON_THE_MOTHERLOAD"] = "A Veia-Mãe"
L["DUNGEON_OPERATION_FLOODGATE"] = "Operação: Comporta"

-- Raids
L["RAID_VAULT_OF_THE_INCARNATES"] = "Cofre dos Encarnados"
L["RAID_ABBERUS_THE_SHADOWED_CRUCIBLE"] = "Aberrus, o Crucível Sombrio"
L["RAID_AMIRDRASSIL_THE_DREAMS_HOPE"] = "Amirdrassil, a Esperança do Sonho"
L["RAID_CASTLE_NATHRIA"] = "Castelo Nathria"
L["RAID_SANCTUM_OF_DOMINATION"] = "Santuário da Dominação"
L["RAID_SEPULCHER_OF_THE_FIRST_ONES"] = "Sepulcro dos Primogênitos"
L["RAID_LIBERATION_OF_UNDERMINE"] = "Liberação da Submina"

-- Settings
L["LEFT_CLICK"] = "Clique esquerdo para abrir portais"
L["RIGHT_CLICK"] = "Clique direito para abrir configurações"
L["SHOW_BACKGROUNDS"] = "Mostrar/Ocultar Fundos"
L["SHOW_MINIMAP"] = "Mostrar/Ocultar Ícone do Minimapa"
L["SETTINGS_TITLE"] = "Configurações dos Portais de Masmorras Míticas"