local L = select(2, ...).L('esMX')

L["MDP_TITLE"] = "Portales de Mazmorras Míticas"

-- Expansiones
L["Cataclysm"] = "Cataclismo"
L["Mists of Pandaria"] = "Mists of Pandaria"
L["Warlords of Draenor"] = "Warlords of Draenor"
L["Legion"] = "Legion"
L["Battle for Azeroth"] = "Battle for Azeroth"
L["Shadowlands"] = "Shadowlands"
L["Dragonflight"] = "Dragonflight"
L["War Within"] = "War Within"
L["Current Season"] = "Temporada Actual"

-- Mazmorras
L["DUNGEON_TEMPLE_OF_THE_JADE_SERPENT"] = "Templo del Dragón de Jade"
L["DUNGEON_SIEGE_OF_NIUZAO"] = "Asedio del Templo de Niuzao"
L["DUNGEON_SCHOLOMANCE"] = "Scholomance"
L["DUNGEON_SCARLET_MONASTERY"] = "Monasterio Escarlata"
L["DUNGEON_SCARLET_HALLS"] = "Salas Escarlata"
L["DUNGEON_GATE_OF_THE_SETTING_SUN"] = "Puerta del Sol Poniente"
L["DUNGEON_MOGUSHAN_PALACE"] = "Palacio Mogu'shan"
L["DUNGEON_SHADO_PAN_MONASTERY"] = "Monasterio del Shadopan"
L["DUNGEON_STORMSTOUT_BREWERY"] = "Cervecería del Trueno"
L["DUNGEON_SHADOWMOON_BURIAL_GROUNDS"] = "Cementerios de Sombraluna"
L["DUNGEON_EVERBLOOM"] = "El Vergel Eterno"
L["DUNGEON_BLOODMAUL_SLAG_MINES"] = "Minas Machacasangre"
L["DUNGEON_AUCHINDOUN"] = "Auchindoun"
L["DUNGEON_SKYREACH"] = "Trecho Celestial"
L["DUNGEON_UPPER_BLACKROCK_SPIRE"] = "Cumbre de Roca Negra Superior"
L["DUNGEON_GRIMRAIL_DEPOT"] = "Depósito de Rieloscuro"
L["DUNGEON_IRON_DOCKS"] = "Muelles de Hierro"
L["DUNGEON_DARKHEART_THICKET"] = "Matorral Corazón Oscuro"
L["DUNGEON_BLACK_ROOK_HOLD"] = "Torreón Grajo Negro"
L["DUNGEON_HALLS_OF_VALOR"] = "Cámaras del Valor"
L["DUNGEON_NELTHARIONS_LAIR"] = "Guarida de Neltharion"
L["DUNGEON_COURT_OF_STARS"] = "Corte de las Estrellas"
L["DUNGEON_KARAZHAN"] = "Karazhan"
L["DUNGEON_ATALDAZAR"] = "Atal'Dazar"
L["DUNGEON_FREEHOLD"] = "Puerto Libre"
L["DUNGEON_WAYCREST_MANOR"] = "Mansión Crestavía"
L["DUNGEON_THE_UNDERROT"] = "Catacumbas Putrefactas"
L["DUNGEON_MECHAGON"] = "Mecandria"
L["DUNGEON_THE_NECROTIC_WAKE"] = "La Estela Necrótica"
L["DUNGEON_PLAGUEFALL"] = "Pesteplaga"
L["DUNGEON_MISTS_OF_TIRNA_SCITHE"] = "Nieblas de Tirna Scithe"
L["DUNGEON_HALLS_OF_ATONEMENT"] = "Salas de la Expiación"
L["DUNGEON_SPIRES_OF_ASCENSION"] = "Agujas de Ascensión"
L["DUNGEON_THEATRE_OF_PAIN"] = "Teatro del Dolor"
L["DUNGEON_DE_OTHER_SIDE"] = "El Otro Lado"
L["DUNGEON_SANGUINE_DEPTHS"] = "Profundidades Sanguinas"
L["DUNGEON_TAZAVESH_THE_VEILED_MARKET"] = "Tazavesh, el Mercado Velado"
L["DUNGEON_RUBY_LIFE_POOLS"] = "Estanques de Vida Rubí"
L["DUNGEON_NOKHUD_OFFENSIVE"] = "Ofensiva Nokhud"
L["DUNGEON_AZURE_VAULT"] = "Bóveda Azur"
L["DUNGEON_ALGETHAR_ACADEMY"] = "Academia Algethar"
L["DUNGEON_ULDAMAN"] = "Uldaman"
L["DUNGEON_NELTHARUS"] = "Neltharus"
L["DUNGEON_BRACKENHIDE_HOLLOW"] = "Hoya Ocultahelecho"
L["DUNGEON_HALLS_OF_INFUSION"] = "Salas de la Infusión"
L["DUNGEON_VORTEX_PINNACLE"] = "Cima del Vórtice"
L["DUNGEON_THRONE_OF_THE_TIDES"] = "Trono de las Mareas"
L["DUNGEON_DAWN_OF_THE_INFINITE"] = "Amanecer del infinito"
L["DUNGEON_CITY_OF_THREADS"] = "Ciudad de los Hilos"
L["DUNGEON_ARA_KARA_CITY_OF_ECHOS"] = "Ara'Kara, Ciudad de los Ecos"
L["DUNGEON_STONEVAULT"] = "Cámaras de Piedra"
L["DUNGEON_DAWNBREAKER"] = "Rompeamaneceres"
L["DUNGEON_THE_ROOKERY"] = "La Aviario"
L["DUNGEON_DARKFLAME_CLEFT"] = "Hendidura Llamaoscura"
L["DUNGEON_CINDERBREW_BREWERY"] = "Cervecería Cenizafermento"
L["DUNGEON_PRIORY_OF_THE_SACRED_FLAME"] = "Priorato de la Llama Sagrada"
L["DUNGEON_GRIM_BATOL"] = "Grim Batol"
L["DUNGEON_SEIGE_OF_BORALUS"] = "Asedio de Boralus"
L["DUNGEON_THE_MOTHERLOAD"] = "La veta madre"
L["DUNGEON_OPERATION_FLOODGATE"] = "Operación: Compuerta"
L["DUNGEON_ECO_DOME_AL_DANI"] = "Eco-Domo Al'dani"

-- Raids
L["RAID_VAULT_OF_THE_INCARNATES"] = "Bóveda de los Encarnados"
L["RAID_ABBERUS_THE_SHADOWED_CRUCIBLE"] = "Aberrus, el Crisol Sombrío"
L["RAID_AMIRDRASSIL_THE_DREAMS_HOPE"] = "Amirdrassil, la Esperanza del Sueño"
L["RAID_CASTLE_NATHRIA"] = "Castillo Nathria"
L["RAID_SANCTUM_OF_DOMINATION"] = "Sagrario de Dominación"
L["RAID_SEPULCHER_OF_THE_FIRST_ONES"] = "Sepulcro de los Primeros"
L["RAID_LIBERATION_OF_UNDERMINE"] = "Liberación de la Submina"
L["RAID_MANAFORGE_OMEGA"] = "Forja de Maná Omega"

-- Settings
L["LEFT_CLICK"] = "Clic izquierdo para abrir los portales"
L["RIGHT_CLICK"] = "Clic derecho para abrir la configuración"
L["SHOW_BACKGROUNDS"] = "Mostrar/Ocultar Fondos"
L["SHOW_MINIMAP"] = "Mostrar/Ocultar Icono del Minimapa"
L["SETTINGS_TITLE"] = "Configuración de los Portales de Mazmorras Míticas"
