local L = select(2, ...).L('koKR')

L["MDP_TITLE"] = "신화 던전 포탈"

-- 확장팩
L["Cataclysm"] = "대격변"
L["Mists of Pandaria"] = "판다리아의 안개"
L["Warlords of Draenor"] = "드레노어의 전쟁군주"
L["Legion"] = "군단"
L["Battle for Azeroth"] = "격전의 아제로스"
L["Shadowlands"] = "어둠땅"
L["Dragonflight"] = "용군단"
L["War Within"] = "War Within"
L["Current Season"] = "현재 시즌"

-- 던전
L["DUNGEON_TEMPLE_OF_THE_JADE_SERPENT"] = "옥룡사"
L["DUNGEON_SIEGE_OF_NIUZAO"] = "니우짜오 사원 공성전"
L["DUNGEON_SCHOLOMANCE"] = "스칼로맨스"
L["DUNGEON_SCARLET_MONASTERY"] = "붉은십자군 수도원"
L["DUNGEON_SCARLET_HALLS"] = "붉은십자군 전당"
L["DUNGEON_GATE_OF_THE_SETTING_SUN"] = "석양문"
L["DUNGEON_MOGUSHAN_PALACE"] = "모구샨 궁전"
L["DUNGEON_SHADO_PAN_MONASTERY"] = "음영파 수도원"
L["DUNGEON_STORMSTOUT_BREWERY"] = "스톰스타우트 양조장"
L["DUNGEON_SHADOWMOON_BURIAL_GROUNDS"] = "어둠달 묘지"
L["DUNGEON_EVERBLOOM"] = "상록숲"
L["DUNGEON_BLOODMAUL_SLAG_MINES"] = "피망치 잿가루 광산"
L["DUNGEON_AUCHINDOUN"] = "아킨둔"
L["DUNGEON_SKYREACH"] = "하늘탑"
L["DUNGEON_UPPER_BLACKROCK_SPIRE"] = "검은바위 첨탑 상층"
L["DUNGEON_GRIMRAIL_DEPOT"] = "파멸철로 정비소"
L["DUNGEON_IRON_DOCKS"] = "강철 선착장"
L["DUNGEON_DARKHEART_THICKET"] = "어둠심장 숲"
L["DUNGEON_BLACK_ROOK_HOLD"] = "검은 떼까마귀 요새"
L["DUNGEON_HALLS_OF_VALOR"] = "용맹의 전당"
L["DUNGEON_NELTHARIONS_LAIR"] = "넬타리온의 둥지"
L["DUNGEON_COURT_OF_STARS"] = "별의 궁정"
L["DUNGEON_KARAZHAN"] = "카라잔"
L["DUNGEON_ATALDAZAR"] = "아탈다자르"
L["DUNGEON_FREEHOLD"] = "자유지대"
L["DUNGEON_WAYCREST_MANOR"] = "웨이크레스트 저택"
L["DUNGEON_THE_UNDERROT"] = "썩은굴"
L["DUNGEON_MECHAGON"] = "메카곤"
L["DUNGEON_THE_NECROTIC_WAKE"] = "죽음의 각성"
L["DUNGEON_PLAGUEFALL"] = "역병 몰락지"
L["DUNGEON_MISTS_OF_TIRNA_SCITHE"] = "티르너 사이드의 안개"
L["DUNGEON_HALLS_OF_ATONEMENT"] = "속죄의 전당"
L["DUNGEON_SPIRES_OF_ASCENSION"] = "승천의 첨탑"
L["DUNGEON_THEATRE_OF_PAIN"] = "고통의 투기장"
L["DUNGEON_DE_OTHER_SIDE"] = "저편"
L["DUNGEON_SANGUINE_DEPTHS"] = "핏빛 심연"
L["DUNGEON_TAZAVESH_THE_VEILED_MARKET"] = "타자베쉬: 가려진 시장"
L["DUNGEON_RUBY_LIFE_POOLS"] = "루비 생명의 웅덩이"
L["DUNGEON_NOKHUD_OFFENSIVE"] = "노쿠드 공격대"
L["DUNGEON_AZURE_VAULT"] = "하늘빛 금고"
L["DUNGEON_ALGETHAR_ACADEMY"] = "알게스아르 아카데미"
L["DUNGEON_ULDAMAN"] = "울다만"
L["DUNGEON_NELTHARUS"] = "넬타루스"
L["DUNGEON_BRACKENHIDE_HOLLOW"] = "브레켄하이드 동굴"
L["DUNGEON_HALLS_OF_INFUSION"] = "주입의 전당"
L["DUNGEON_VORTEX_PINNACLE"] = "소용돌이 누각"
L["DUNGEON_THRONE_OF_THE_TIDES"] = "파도의 왕좌"
L["DUNGEON_DAWN_OF_THE_INFINITE"] = "무한의 새벽"
L["DUNGEON_CITY_OF_THREADS"] = "실의 도시"
L["DUNGEON_ARA_KARA_CITY_OF_ECHOS"] = "아라카라: 메아리의 도시"
L["DUNGEON_STONEVAULT"] = "돌금고"
L["DUNGEON_DAWNBREAKER"] = "새벽파괴자"
L["DUNGEON_THE_ROOKERY"] = "마루"
L["DUNGEON_DARKFLAME_CLEFT"] = "어둠불 근처"
L["DUNGEON_CINDERBREW_BREWERY"] = "잿빛 양조장"
L["DUNGEON_PRIORY_OF_THE_SACRED_FLAME"] = "신성한 불길 수도원"
L["DUNGEON_GRIM_BATOL"] = "그림 바톨"
L["DUNGEON_SEIGE_OF_BORALUS"] = "보랄러스 공성전"
L["DUNGEON_THE_MOTHERLOAD"] = "주 광맥"
L["DUNGEON_OPERATION_FLOODGATE"] = "작전: 수문"
L["DUNGEON_ECO_DOME_AL_DANI"] = "에코 돔 알다니"

-- Raids
L["RAID_VAULT_OF_THE_INCARNATES"] = "현신의 금고"
L["RAID_ABBERUS_THE_SHADOWED_CRUCIBLE"] = "어버러스, 암흑의 도가니"
L["RAID_AMIRDRASSIL_THE_DREAMS_HOPE"] = "아미르드라실, 꿈의 희망"
L["RAID_CASTLE_NATHRIA"] = "나스리아 성채"
L["RAID_SANCTUM_OF_DOMINATION"] = "지배의 성소"
L["RAID_SEPULCHER_OF_THE_FIRST_ONES"] = "초월자의 묘지"
L["RAID_LIBERATION_OF_UNDERMINE"] = "해방: 하부광산"
L["RAID_MANAFORGE_OMEGA"] = "마나포지 오메가"

-- Settings
L["LEFT_CLICK"] = "왼쪽 클릭으로 포탈 열기"
L["RIGHT_CLICK"] = "오른쪽 클릭으로 설정 열기"
L["SHOW_BACKGROUNDS"] = "배경 표시/숨기기"
L["SHOW_MINIMAP"] = "미니맵 아이콘 표시/숨기기"
L["SETTINGS_TITLE"] = "신화 던전 포탈 설정"
