local L = select(2, ...).L('itIT')

L["MDP_TITLE"] = "Portali Spedizioni Mitiche"

-- Espansioni
L["Cataclysm"] = "Cataclysm"
L["Mists of Pandaria"] = "Mists of Pandaria"
L["Warlords of Draenor"] = "Warlords of Draenor"
L["Legion"] = "Legion"
L["Battle for Azeroth"] = "Battle for Azeroth"
L["Shadowlands"] = "Shadowlands"
L["Dragonflight"] = "Dragonflight"
L["War Within"] = "War Within"
L["Current Season"] = "Stagione Corrente"

-- Spedizioni
L["DUNGEON_TEMPLE_OF_THE_JADE_SERPENT"] = "Tempio della Serpe di Giada"
L["DUNGEON_SIEGE_OF_NIUZAO"] = "Assedio del Tempio di Niuzao"
L["DUNGEON_SCHOLOMANCE"] = "Scholomance"
L["DUNGEON_SCARLET_MONASTERY"] = "Monastero Scarlatto"
L["DUNGEON_SCARLET_HALLS"] = "Sale Scarlatte"
L["DUNGEON_GATE_OF_THE_SETTING_SUN"] = "Porta del Sole Calante"
L["DUNGEON_MOGUSHAN_PALACE"] = "Palazzo Mogu'shan"
L["DUNGEON_SHADO_PAN_MONASTERY"] = "Monastero degli Shandaren"
L["DUNGEON_STORMSTOUT_BREWERY"] = "Birrificio Triplo Malto"
L["DUNGEON_SHADOWMOON_BURIAL_GROUNDS"] = "Necropoli dei Torvaluna"
L["DUNGEON_EVERBLOOM"] = "Verdeterno"
L["DUNGEON_BLOODMAUL_SLAG_MINES"] = "Miniere di Scorie di Roccianera"
L["DUNGEON_AUCHINDOUN"] = "Auchindoun"
L["DUNGEON_SKYREACH"] = "Vetta dei Cieli"
L["DUNGEON_UPPER_BLACKROCK_SPIRE"] = "Bastioni di Roccianera Superiori"
L["DUNGEON_GRIMRAIL_DEPOT"] = "Scalo di Grimrail"
L["DUNGEON_IRON_DOCKS"] = "Darsena di Ferro"
L["DUNGEON_DARKHEART_THICKET"] = "Boschetto Cuortetro"
L["DUNGEON_BLACK_ROOK_HOLD"] = "Forte Corvonero"
L["DUNGEON_HALLS_OF_VALOR"] = "Sale del Valore"
L["DUNGEON_NELTHARIONS_LAIR"] = "Antro di Neltharion"
L["DUNGEON_COURT_OF_STARS"] = "Corte delle Stelle"
L["DUNGEON_KARAZHAN"] = "Karazhan"
L["DUNGEON_ATALDAZAR"] = "Atal'Dazar"
L["DUNGEON_FREEHOLD"] = "Covo della Libertà"
L["DUNGEON_WAYCREST_MANOR"] = "Maniero dei Crestabianca"
L["DUNGEON_THE_UNDERROT"] = "Grottamarcia"
L["DUNGEON_MECHAGON"] = "Meccagon"
L["DUNGEON_THE_NECROTIC_WAKE"] = "Risveglio Necrotico"
L["DUNGEON_PLAGUEFALL"] = "Caduta della Pestilenza"
L["DUNGEON_MISTS_OF_TIRNA_SCITHE"] = "Nebbie di Tirna Scithe"
L["DUNGEON_HALLS_OF_ATONEMENT"] = "Sale della Redenzione"
L["DUNGEON_SPIRES_OF_ASCENSION"] = "Guglie dell'Ascensione"
L["DUNGEON_THEATRE_OF_PAIN"] = "Teatro del Dolore"
L["DUNGEON_DE_OTHER_SIDE"] = "Oltremondo"
L["DUNGEON_SANGUINE_DEPTHS"] = "Profondità Sanguigne"
L["DUNGEON_TAZAVESH_THE_VEILED_MARKET"] = "Tazavesh, il Mercato Velato"
L["DUNGEON_RUBY_LIFE_POOLS"] = "Bacini della Vita di Rubino"
L["DUNGEON_NOKHUD_OFFENSIVE"] = "Offensiva di Nokhud"
L["DUNGEON_AZURE_VAULT"] = "Cripta Azzurra"
L["DUNGEON_ALGETHAR_ACADEMY"] = "Accademia di Algethar"
L["DUNGEON_ULDAMAN"] = "Uldaman"
L["DUNGEON_NELTHARUS"] = "Neltharus"
L["DUNGEON_BRACKENHIDE_HOLLOW"] = "Anfratto di Nascondiargento"
L["DUNGEON_HALLS_OF_INFUSION"] = "Sale dell'Infusione"
L["DUNGEON_VORTEX_PINNACLE"] = "Pinnacolo del Vortice"
L["DUNGEON_THRONE_OF_THE_TIDES"] = "Trono delle Maree"
L["DUNGEON_DAWN_OF_THE_INFINITE"] = "L'alba dell'infinito"
L["DUNGEON_CITY_OF_THREADS"] = "Città dei Fili"
L["DUNGEON_ARA_KARA_CITY_OF_ECHOS"] = "Ara'Kara, Città degli Echi"
L["DUNGEON_STONEVAULT"] = "Volta di Pietra"
L["DUNGEON_DAWNBREAKER"] = "Frangialba"
L["DUNGEON_THE_ROOKERY"] = "Il Nido"
L["DUNGEON_DARKFLAME_CLEFT"] = "Fenditura Fiammanera"
L["DUNGEON_CINDERBREW_BREWERY"] = "Birrificio Cenerefermento"
L["DUNGEON_PRIORY_OF_THE_SACRED_FLAME"] = "Priorato della Fiamma Sacra"
L["DUNGEON_GRIM_BATOL"] = "Grim Batol"
L["DUNGEON_SEIGE_OF_BORALUS"] = "Assedio di Boralus"
L["DUNGEON_THE_MOTHERLOAD"] = "La vena madre"
L["DUNGEON_OPERATION_FLOODGATE"] = "Operazione: Chiusa"
L["DUNGEON_ECO_DOME_AL_DANI"] = "Eco-Cupola Al'dani"

-- Raids
L["RAID_VAULT_OF_THE_INCARNATES"] = "Volta degli Incarnati"
L["RAID_ABBERUS_THE_SHADOWED_CRUCIBLE"] = "Aberrus, il Crogiolo Oscuro"
L["RAID_AMIRDRASSIL_THE_DREAMS_HOPE"] = "Amirdrassil, la Speranza del Sogno"
L["RAID_CASTLE_NATHRIA"] = "Castello di Nathria"
L["RAID_SANCTUM_OF_DOMINATION"] = "Santuario del Dominio"
L["RAID_SEPULCHER_OF_THE_FIRST_ONES"] = "Sepolcro dei Primi"
L["RAID_LIBERATION_OF_UNDERMINE"] = "Liberazione della Sottominiera"
L["RAID_MANAFORGE_OMEGA"] = "Forgia di Mana Omega"

-- Settings
L["SETTINGS_TITLE"] = "Impostazioni Portali Spedizioni Mitiche"
L["LEFT_CLICK"] = "Clicca sinistro per aprire i portali"
L["RIGHT_CLICK"] = "Clicca destro per aprire le impostazioni"
L["SHOW_BACKGROUNDS"] = "Mostra/Nascondi Sfondi"
L["SHOW_MINIMAP"] = "Mostra/Nascondi Icona Minimappa"
