name: Release Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel
        
      - name: Extract Version from TOC file
        run: |
          VERSION=$(grep '## Version:' MythicDungeonPortals.toc | cut -d ' ' -f 3)
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"

      - name: Zip the project
        run: |
          mkdir MythicDungeonPortals
          find . -maxdepth 1 ! -name 'MythicDungeonPortals' ! -name '.' ! -name '.git' -exec mv {} MythicDungeonPortals/ \;
          zip -r "MythicDungeonPortals-${{ env.version }}.zip" MythicDungeonPortals

      - name: Check if Tag Exists
        id: check-tag
        run: |
          if git rev-parse "v${{ env.version }}" >/dev/null 2>&1; then
              echo "Tag v${{ env.version }} already exists!"
              echo "skip=true" >> $GITHUB_ENV
          else
              echo "skip=false" >> $GITHUB_ENV
          fi

      - name: Create a new tag
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && env.skip == 'false'
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: none
          custom_tag: ${{ env.version }}

      - name: Create Release
        if: env.skip == 'false'
        uses: softprops/action-gh-release@v1
        with:
          files: "MythicDungeonPortals-${{ env.version }}.zip"
          tag_name: v${{ env.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
